### ISSUE TITLE
Promises Not Resolving

### ISSUE THREAD

**Issue by vwnj84** [vwnj84/gh-bulk-user-add#1]
❯ node index.js -a -o msi-learning -r Apr29 -f Dev1.txt -p push
{"add":true,"org":"msi-learning","repo":"Apr29","file":"Dev1.txt","permission":"push"}
[
  'BHVX48_moto', 'APP021_moto',
  'QGK436_moto', 'VHWP64_moto',
  'MQDB48_moto', 'TJX346_moto',
  'WBK436_moto', 'DXG847_moto',
  'QNJC78_moto', 'WQKG73_moto',
  'MNWF43_moto', 'TGFC46_moto',
  'GTHW87_moto', 'pqcb83_moto',
  'KVHC87_moto', 'MWCV64_moto',
  'VDM637_moto', 'DMKJ74_moto',
  'GNWX84_moto', 'KTJ768_moto',
  'KQCB73_moto', 'KDQ364_moto',
  'FMQX74_moto', 'NTBH34_moto',
  'CDQ487_moto'
]
Promise { <pending> }
Error adding BHVX48_moto to repo Apr29 in org msi-learning => TypeError: Cannot read properties of undefined (reading 'html_url')
Promise { undefined }
Error adding APP021_moto to repo Apr29 in org msi-learning => TypeError: Cannot read properties of undefined (reading 'html_url')
Promise { undefined }
Error adding QGK436_moto to repo Apr29 in org msi-learning => TypeError: Cannot read properties of undefined (reading 'html_url')

**Comment by decyjphr** [comment]
@vwnj84 According to the [doc](https://docs.github.com/en/rest/reference/collaborators#add-a-repository-collaborator)  the response field should be data.repository.html_url
So try changing the line https://github.com/vwnj84/gh-bulk-user-add/blob/a3ae46db4c150fe10cb11bf4516c076f0cdfdcde/index.js#L116 and see if that resolves the issue

**Comment by vwnj84** [comment]
Ended up just removing the reference to the returned json to get it working. I may add it back later, don't know.
